/**
 * Mock Activity Data
 * Sample data for Activity Log / Audit Trail
 */

import type { ActivityEntry, ActivityStats } from '@/types/activity';

// ============================================================================
// Activity Entries
// ============================================================================

export const mockActivityEntries: ActivityEntry[] = [
  // Today
  {
    id: 'act-1',
    type: 'task_completed',
    category: 'tasks',
    title: 'Task Completed',
    description: 'Completed annual portfolio review for Michael Johnson',
    actor: 'user',
    actorName: 'You',
    timestamp: new Date(Date.now() - 1800000).toISOString(), // 30 mins ago
    clientId: 'client-1',
    clientName: 'Michael Johnson',
    taskId: 'task-1',
    taskTitle: 'Annual Portfolio Review',
    isRead: false,
  },
  {
    id: 'act-2',
    type: 'automation_executed',
    category: 'automations',
    title: 'Automation Executed',
    description: 'Birthday greeting email sent automatically',
    actor: 'automation',
    actorName: 'Birthday Greetings Automation',
    timestamp: new Date(Date.now() - 3600000).toISOString(), // 1 hour ago
    clientId: 'client-3',
    clientName: 'Sarah Chen',
    automationId: 'auto-1',
    automationName: 'Birthday Greetings',
    isRead: false,
  },
  {
    id: 'act-3',
    type: 'opportunity_surfaced',
    category: 'opportunities',
    title: 'New Opportunity',
    description: 'RRSP contribution opportunity identified for Robert Thompson',
    actor: 'system',
    timestamp: new Date(Date.now() - 7200000).toISOString(), // 2 hours ago
    clientId: 'client-2',
    clientName: 'Robert Thompson',
    opportunityId: 'opp-1',
    opportunityTitle: 'RRSP Contribution Room Available',
    isRead: true,
  },
  {
    id: 'act-4',
    type: 'email_sent',
    category: 'communications',
    title: 'Email Sent',
    description: 'Quarterly investment report sent to Emily Davis',
    actor: 'user',
    actorName: 'You',
    timestamp: new Date(Date.now() - 10800000).toISOString(), // 3 hours ago
    clientId: 'client-4',
    clientName: 'Emily Davis',
    isRead: true,
  },
  {
    id: 'act-5',
    type: 'integration_synced',
    category: 'integrations',
    title: 'Integration Synced',
    description: 'Google Drive sync completed successfully',
    actor: 'system',
    timestamp: new Date(Date.now() - 14400000).toISOString(), // 4 hours ago
    integrationId: 'int-1',
    integrationName: 'Google Drive',
    details: {
      recordsSynced: 24,
      newRecords: 3,
      updatedRecords: 21,
    },
    isRead: true,
  },
  // Yesterday
  {
    id: 'act-6',
    type: 'client_updated',
    category: 'clients',
    title: 'Client Updated',
    description: 'Updated contact information for James Wilson',
    actor: 'user',
    actorName: 'You',
    timestamp: new Date(Date.now() - 86400000).toISOString(), // 1 day ago
    clientId: 'client-5',
    clientName: 'James Wilson',
    changes: [
      { field: 'phone', fieldLabel: 'Phone', oldValue: '416-555-0100', newValue: '416-555-0199' },
      { field: 'email', fieldLabel: 'Email', oldValue: 'james.w@email.com', newValue: 'james.wilson@newmail.com' },
    ],
    isRead: true,
  },
  {
    id: 'act-7',
    type: 'task_created',
    category: 'tasks',
    title: 'Task Created',
    description: 'New task: Schedule insurance review with Patricia Brown',
    actor: 'system',
    timestamp: new Date(Date.now() - 90000000).toISOString(), // ~1 day ago
    clientId: 'client-6',
    clientName: 'Patricia Brown',
    taskId: 'task-2',
    taskTitle: 'Insurance Review Meeting',
    isRead: true,
  },
  {
    id: 'act-8',
    type: 'review_approved',
    category: 'data',
    title: 'Data Review Approved',
    description: 'Approved extracted client data from uploaded document',
    actor: 'user',
    actorName: 'You',
    timestamp: new Date(Date.now() - 93600000).toISOString(),
    clientId: 'client-7',
    clientName: 'David Martinez',
    details: {
      documentName: 'Investment_Statement_Q3.pdf',
      fieldsExtracted: 12,
    },
    isRead: true,
  },
  {
    id: 'act-9',
    type: 'meeting_scheduled',
    category: 'communications',
    title: 'Meeting Scheduled',
    description: 'Annual review meeting scheduled with Jennifer Lee',
    actor: 'user',
    actorName: 'You',
    timestamp: new Date(Date.now() - 100800000).toISOString(),
    clientId: 'client-8',
    clientName: 'Jennifer Lee',
    details: {
      meetingDate: new Date(Date.now() + 604800000).toISOString(),
      duration: 60,
      type: 'Annual Review',
    },
    isRead: true,
  },
  // 2 Days ago
  {
    id: 'act-10',
    type: 'opportunity_actioned',
    category: 'opportunities',
    title: 'Opportunity Actioned',
    description: 'Started workflow for GIC renewal with Michael Anderson',
    actor: 'user',
    actorName: 'You',
    timestamp: new Date(Date.now() - 172800000).toISOString(), // 2 days ago
    clientId: 'client-9',
    clientName: 'Michael Anderson',
    opportunityId: 'opp-2',
    opportunityTitle: 'GIC Renewal',
    isRead: true,
  },
  {
    id: 'act-11',
    type: 'document_uploaded',
    category: 'documents',
    title: 'Document Uploaded',
    description: 'Uploaded financial planning document for Susan Taylor',
    actor: 'user',
    actorName: 'You',
    timestamp: new Date(Date.now() - 180000000).toISOString(),
    clientId: 'client-10',
    clientName: 'Susan Taylor',
    documentId: 'doc-1',
    documentName: 'Financial_Plan_2025.pdf',
    isRead: true,
  },
  {
    id: 'act-12',
    type: 'automation_approved',
    category: 'automations',
    title: 'Automation Approved',
    description: 'Approved new automation: Quarterly Statement Distribution',
    actor: 'user',
    actorName: 'You',
    timestamp: new Date(Date.now() - 187200000).toISOString(),
    automationId: 'auto-2',
    automationName: 'Quarterly Statement Distribution',
    isRead: true,
  },
  {
    id: 'act-13',
    type: 'integration_error',
    category: 'integrations',
    title: 'Integration Error',
    description: 'Outlook Calendar sync failed - re-authentication required',
    actor: 'system',
    timestamp: new Date(Date.now() - 194400000).toISOString(),
    integrationId: 'int-2',
    integrationName: 'Outlook Calendar',
    isError: true,
    isImportant: true,
    details: {
      errorCode: 'AUTH_EXPIRED',
      errorMessage: 'OAuth token has expired',
    },
    isRead: false,
  },
  // 3 Days ago
  {
    id: 'act-14',
    type: 'client_created',
    category: 'clients',
    title: 'New Client Added',
    description: 'New client profile created for Thomas Brown',
    actor: 'user',
    actorName: 'You',
    timestamp: new Date(Date.now() - 259200000).toISOString(), // 3 days ago
    clientId: 'client-11',
    clientName: 'Thomas Brown',
    isRead: true,
  },
  {
    id: 'act-15',
    type: 'data_imported',
    category: 'data',
    title: 'Data Imported',
    description: 'Successfully imported 15 client records from CSV',
    actor: 'user',
    actorName: 'You',
    timestamp: new Date(Date.now() - 266400000).toISOString(),
    details: {
      fileName: 'client_list.csv',
      totalRecords: 15,
      newRecords: 12,
      updatedRecords: 3,
      skippedRecords: 0,
    },
    isRead: true,
  },
  {
    id: 'act-16',
    type: 'note_added',
    category: 'clients',
    title: 'Note Added',
    description: 'Added note to client file for Lisa Wang',
    actor: 'user',
    actorName: 'You',
    timestamp: new Date(Date.now() - 280800000).toISOString(),
    clientId: 'client-12',
    clientName: 'Lisa Wang',
    details: {
      notePreview: 'Discussed retirement timeline - planning to retire in 5 years...',
    },
    isRead: true,
  },
  // 4 Days ago
  {
    id: 'act-17',
    type: 'call_logged',
    category: 'communications',
    title: 'Call Logged',
    description: 'Phone call with Richard Kim regarding investment changes',
    actor: 'user',
    actorName: 'You',
    timestamp: new Date(Date.now() - 345600000).toISOString(), // 4 days ago
    clientId: 'client-13',
    clientName: 'Richard Kim',
    details: {
      duration: 25,
      outcome: 'Scheduled follow-up meeting',
    },
    isRead: true,
  },
  {
    id: 'act-18',
    type: 'opportunity_dismissed',
    category: 'opportunities',
    title: 'Opportunity Dismissed',
    description: 'Dismissed insurance upsell opportunity for Nancy Clark',
    actor: 'user',
    actorName: 'You',
    timestamp: new Date(Date.now() - 352800000).toISOString(),
    clientId: 'client-14',
    clientName: 'Nancy Clark',
    opportunityId: 'opp-3',
    opportunityTitle: 'Life Insurance Review',
    details: {
      dismissReason: 'Client recently purchased coverage elsewhere',
    },
    isRead: true,
  },
  // 5 Days ago
  {
    id: 'act-19',
    type: 'settings_changed',
    category: 'system',
    title: 'Settings Updated',
    description: 'Updated notification preferences',
    actor: 'user',
    actorName: 'You',
    timestamp: new Date(Date.now() - 432000000).toISOString(), // 5 days ago
    changes: [
      { field: 'emailNotifications', fieldLabel: 'Email Notifications', oldValue: true, newValue: false },
    ],
    isRead: true,
  },
  {
    id: 'act-20',
    type: 'integration_connected',
    category: 'integrations',
    title: 'Integration Connected',
    description: 'Successfully connected Dropbox integration',
    actor: 'user',
    actorName: 'You',
    timestamp: new Date(Date.now() - 439200000).toISOString(),
    integrationId: 'int-3',
    integrationName: 'Dropbox',
    isRead: true,
  },
  // Older entries
  {
    id: 'act-21',
    type: 'login',
    category: 'auth',
    title: 'Login',
    description: 'Logged in from Chrome on Windows',
    actor: 'user',
    actorName: 'You',
    timestamp: new Date(Date.now() - 518400000).toISOString(), // 6 days ago
    details: {
      browser: 'Chrome',
      os: 'Windows',
      location: 'Toronto, ON',
    },
    isRead: true,
  },
  {
    id: 'act-22',
    type: 'data_exported',
    category: 'data',
    title: 'Data Exported',
    description: 'Exported client list to Excel',
    actor: 'user',
    actorName: 'You',
    timestamp: new Date(Date.now() - 604800000).toISOString(), // 7 days ago
    details: {
      format: 'xlsx',
      recordCount: 247,
    },
    isRead: true,
  },
  {
    id: 'act-23',
    type: 'automation_paused',
    category: 'automations',
    title: 'Automation Paused',
    description: 'Paused Follow-up Reminder automation',
    actor: 'user',
    actorName: 'You',
    timestamp: new Date(Date.now() - 691200000).toISOString(), // 8 days ago
    automationId: 'auto-3',
    automationName: 'Follow-up Reminder',
    isRead: true,
  },
  {
    id: 'act-24',
    type: 'system_event',
    category: 'system',
    title: 'System Maintenance',
    description: 'Scheduled system maintenance completed successfully',
    actor: 'system',
    timestamp: new Date(Date.now() - 777600000).toISOString(), // 9 days ago
    isRead: true,
  },
  {
    id: 'act-25',
    type: 'review_rejected',
    category: 'data',
    title: 'Data Review Rejected',
    description: 'Rejected incorrect data extraction from email',
    actor: 'user',
    actorName: 'You',
    timestamp: new Date(Date.now() - 864000000).toISOString(), // 10 days ago
    details: {
      reason: 'Extracted data did not match client',
      sourceName: 'Email from broker',
    },
    isRead: true,
  },
];

// ============================================================================
// Activity Stats
// ============================================================================

export const mockActivityStats: ActivityStats = {
  totalEntries: 25,
  entriesThisWeek: 15,
  entriesThisMonth: 25,
  byCategory: {
    clients: 4,
    tasks: 2,
    opportunities: 4,
    automations: 3,
    integrations: 4,
    data: 3,
    communications: 3,
    documents: 1,
    auth: 1,
    system: 2,
  },
  byType: {
    client_created: 1,
    client_updated: 1,
    client_archived: 0,
    contact_added: 0,
    note_added: 1,
    task_created: 1,
    task_completed: 1,
    task_assigned: 0,
    opportunity_surfaced: 1,
    opportunity_actioned: 1,
    opportunity_dismissed: 1,
    automation_executed: 1,
    automation_approved: 1,
    automation_paused: 1,
    integration_connected: 1,
    integration_synced: 1,
    integration_error: 1,
    data_imported: 1,
    data_exported: 1,
    review_approved: 1,
    review_rejected: 1,
    email_sent: 1,
    email_received: 0,
    call_logged: 1,
    meeting_scheduled: 1,
    document_uploaded: 1,
    document_shared: 0,
    login: 1,
    logout: 0,
    settings_changed: 1,
    system_event: 1,
  },
  byActor: {
    user: 18,
    system: 5,
    automation: 2,
  },
  errorCount: 1,
  importantCount: 1,
};
