// Mock automations data for Ciri
import {
  AutomationSuggestion,
  ActiveAutomation,
  AutomationException,
  AdaptationLogEntry,
  AutomationActivityEntry,
} from '@/types/automation';

// Automation suggestions waiting for approval
export const mockAutomationSuggestions: AutomationSuggestion[] = [
  {
    id: 'sug-001',
    patternDescription: 'You send birthday emails to clients within 2 days of their birthday',
    automationDescription: 'Automatically draft and queue birthday emails for clients 1 day before their birthday',
    expectedBenefit: 'Save 15 minutes per week on birthday outreach',
    category: 'client_outreach',
    triggerType: 'time_based',
    actionType: 'send_email',
    detectedAt: '2024-12-14T10:00:00Z',
    occurrenceCount: 23,
    confidenceScore: 92,
    status: 'pending',
    affectedClients: ['c-001', 'c-002', 'c-003'],
    estimatedTimeSaved: 15,
    example: {
      trigger: 'Client birthday is tomorrow',
      action: 'Draft personalized birthday email using client name and relationship history',
    },
  },
  {
    id: 'sug-002',
    patternDescription: 'You follow up with clients 3 days after sending portfolio reviews',
    automationDescription: 'Create follow-up tasks automatically 3 days after portfolio review emails',
    expectedBenefit: 'Never miss a follow-up opportunity',
    category: 'follow_up',
    triggerType: 'event_based',
    actionType: 'create_task',
    detectedAt: '2024-12-13T14:30:00Z',
    occurrenceCount: 18,
    confidenceScore: 87,
    status: 'pending',
    estimatedTimeSaved: 20,
    example: {
      trigger: 'Portfolio review email sent to client',
      action: 'Create follow-up call task in 3 days',
    },
  },
  {
    id: 'sug-003',
    patternDescription: 'You update client risk profiles after significant market events',
    automationDescription: 'Flag clients for risk profile review when market volatility exceeds 2%',
    expectedBenefit: 'Proactive client care during market turbulence',
    category: 'compliance',
    triggerType: 'condition_based',
    actionType: 'create_task',
    detectedAt: '2024-12-12T09:15:00Z',
    occurrenceCount: 8,
    confidenceScore: 75,
    status: 'pending',
    estimatedTimeSaved: 30,
    example: {
      trigger: 'S&P 500 drops more than 2% in a day',
      action: 'Create task to review high-risk client portfolios',
    },
  },
  {
    id: 'sug-004',
    patternDescription: 'You schedule annual reviews 30 days before policy anniversaries',
    automationDescription: 'Auto-create annual review tasks 30 days before client policy anniversaries',
    expectedBenefit: 'Ensure timely annual reviews for all clients',
    category: 'task_management',
    triggerType: 'time_based',
    actionType: 'create_task',
    detectedAt: '2024-12-10T11:00:00Z',
    occurrenceCount: 45,
    confidenceScore: 95,
    status: 'pending',
    estimatedTimeSaved: 25,
    example: {
      trigger: '30 days before client policy anniversary',
      action: 'Create annual review task with client history attached',
    },
  },
  {
    id: 'sug-005',
    patternDescription: 'You send weekly portfolio summaries every Monday morning',
    automationDescription: 'Generate and send weekly portfolio summary reports every Monday at 8 AM',
    expectedBenefit: 'Consistent client communication without manual effort',
    category: 'reporting',
    triggerType: 'time_based',
    actionType: 'generate_report',
    detectedAt: '2024-12-08T16:00:00Z',
    occurrenceCount: 12,
    confidenceScore: 88,
    status: 'rejected',
    estimatedTimeSaved: 45,
    example: {
      trigger: 'Every Monday at 8:00 AM',
      action: 'Generate and email weekly portfolio performance summary',
    },
  },
];

// Currently active automations
export const mockActiveAutomations: ActiveAutomation[] = [
  {
    id: 'auto-001',
    name: 'New Client Welcome Sequence',
    description: 'Send welcome email and create onboarding tasks for new clients',
    category: 'client_outreach',
    triggerType: 'event_based',
    triggerConfig: {
      event: 'client_created',
      delay: 0,
    },
    actionType: 'send_email',
    actionConfig: {
      template: 'welcome_email',
      createFollowUpTask: true,
      followUpDays: 7,
    },
    status: 'running',
    createdAt: '2024-11-01T10:00:00Z',
    createdBy: 'advisor@example.com',
    lastRunAt: '2024-12-14T15:30:00Z',
    nextRunAt: undefined,
    successCount: 34,
    failureCount: 0,
    exceptionCount: 2,
    safetyBounds: {
      maxPerDay: 10,
      allowedHours: { start: 8, end: 18 },
      cooldownPeriod: 24,
    },
    isSystemGenerated: false,
  },
  {
    id: 'auto-002',
    name: 'Meeting Reminder Notifications',
    description: 'Send reminder emails 24 hours before scheduled client meetings',
    category: 'client_outreach',
    triggerType: 'time_based',
    triggerConfig: {
      beforeEvent: 'meeting',
      hours: 24,
    },
    actionType: 'send_notification',
    actionConfig: {
      type: 'email',
      includeAgenda: true,
      includeLocation: true,
    },
    status: 'running',
    createdAt: '2024-10-15T08:00:00Z',
    createdBy: 'advisor@example.com',
    lastRunAt: '2024-12-15T08:00:00Z',
    nextRunAt: '2024-12-15T14:00:00Z',
    successCount: 156,
    failureCount: 3,
    exceptionCount: 1,
    safetyBounds: {
      maxPerDay: 20,
      allowedDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
      allowedHours: { start: 7, end: 20 },
    },
    isSystemGenerated: true,
    sourcePattern: 'Detected from 45 manual reminder sends',
  },
  {
    id: 'auto-003',
    name: 'Document Expiry Alerts',
    description: 'Create tasks when client documents are approaching expiry',
    category: 'compliance',
    triggerType: 'condition_based',
    triggerConfig: {
      condition: 'document_expiry',
      daysBeforeExpiry: 30,
    },
    actionType: 'create_task',
    actionConfig: {
      priority: 'high',
      assignTo: 'self',
      includeDocumentLink: true,
    },
    status: 'running',
    createdAt: '2024-09-01T12:00:00Z',
    createdBy: 'advisor@example.com',
    lastRunAt: '2024-12-15T06:00:00Z',
    nextRunAt: '2024-12-16T06:00:00Z',
    successCount: 89,
    failureCount: 0,
    exceptionCount: 0,
    safetyBounds: {
      maxPerDay: 15,
    },
    isSystemGenerated: false,
  },
  {
    id: 'auto-004',
    name: 'Post-Meeting Notes Reminder',
    description: 'Create task to add meeting notes 1 hour after meetings end',
    category: 'task_management',
    triggerType: 'event_based',
    triggerConfig: {
      event: 'meeting_ended',
      delayMinutes: 60,
    },
    actionType: 'create_task',
    actionConfig: {
      title: 'Add meeting notes',
      priority: 'medium',
      dueInHours: 24,
    },
    status: 'paused',
    createdAt: '2024-11-15T09:00:00Z',
    createdBy: 'advisor@example.com',
    lastRunAt: '2024-12-10T17:00:00Z',
    successCount: 28,
    failureCount: 1,
    exceptionCount: 5,
    safetyBounds: {
      maxPerDay: 10,
      allowedDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
    },
    isSystemGenerated: true,
    sourcePattern: 'Detected from manual note-taking pattern',
  },
  {
    id: 'auto-005',
    name: 'Quarterly Review Scheduler',
    description: 'Schedule quarterly review meetings with top-tier clients',
    category: 'client_outreach',
    triggerType: 'time_based',
    triggerConfig: {
      schedule: 'quarterly',
      clientTier: 'premium',
    },
    actionType: 'schedule_meeting',
    actionConfig: {
      duration: 60,
      type: 'portfolio_review',
      sendInvite: true,
    },
    status: 'running',
    createdAt: '2024-08-01T10:00:00Z',
    createdBy: 'advisor@example.com',
    lastRunAt: '2024-12-01T09:00:00Z',
    nextRunAt: '2025-01-01T09:00:00Z',
    successCount: 48,
    failureCount: 2,
    exceptionCount: 3,
    safetyBounds: {
      maxPerWeek: 15,
      requireConfirmationAbove: 5,
      allowedDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
      allowedHours: { start: 9, end: 17 },
    },
    isSystemGenerated: false,
  },
];

// Automation exceptions requiring attention
export const mockAutomationExceptions: AutomationException[] = [
  {
    id: 'exc-001',
    automationId: 'auto-001',
    automationName: 'New Client Welcome Sequence',
    reason: 'Client email bounced',
    details: 'The welcome email to Sarah Chen could not be delivered - invalid email address',
    occurredAt: '2024-12-14T15:35:00Z',
    status: 'pending',
    affectedClientId: 'c-002',
    affectedClientName: 'Sarah Chen',
    severity: 'medium',
    suggestedAction: 'Verify and update client email address',
  },
  {
    id: 'exc-002',
    automationId: 'auto-005',
    automationName: 'Quarterly Review Scheduler',
    reason: 'Calendar conflict detected',
    details: 'Could not schedule meeting with Michael Johnson - no available slots in the next 2 weeks',
    occurredAt: '2024-12-13T10:00:00Z',
    status: 'pending',
    affectedClientId: 'c-001',
    affectedClientName: 'Michael Johnson',
    severity: 'low',
    suggestedAction: 'Manually find alternative meeting time',
  },
  {
    id: 'exc-003',
    automationId: 'auto-002',
    automationName: 'Meeting Reminder Notifications',
    reason: 'Meeting was cancelled after reminder sent',
    details: 'Reminder was sent but the meeting was cancelled 2 hours later',
    occurredAt: '2024-12-12T14:00:00Z',
    status: 'resolved',
    resolvedAt: '2024-12-12T14:30:00Z',
    resolvedBy: 'advisor@example.com',
    resolution: 'Sent apology email to client',
    affectedClientId: 'c-003',
    affectedClientName: 'Robert Williams',
    severity: 'low',
  },
  {
    id: 'exc-004',
    automationId: 'auto-004',
    automationName: 'Post-Meeting Notes Reminder',
    reason: 'Duplicate task created',
    details: 'A manual task already existed for the same meeting notes',
    occurredAt: '2024-12-10T18:00:00Z',
    status: 'ignored',
    severity: 'low',
    suggestedAction: 'No action needed - automation paused to investigate',
  },
  {
    id: 'exc-005',
    automationId: 'auto-001',
    automationName: 'New Client Welcome Sequence',
    reason: 'Template variables not found',
    details: 'Client portfolio value was missing, could not personalize email',
    occurredAt: '2024-12-08T11:00:00Z',
    status: 'resolved',
    resolvedAt: '2024-12-08T12:00:00Z',
    resolvedBy: 'advisor@example.com',
    resolution: 'Updated client record and resent email',
    affectedClientId: 'c-004',
    affectedClientName: 'Emily Davis',
    severity: 'medium',
  },
];

// Adaptation log entries
export const mockAdaptationLogs: AdaptationLogEntry[] = [
  {
    id: 'adapt-001',
    type: 'pattern_detected',
    title: 'Birthday Email Pattern',
    description: 'Detected consistent pattern of sending birthday emails within 2 days of client birthdays',
    timestamp: '2024-12-14T10:00:00Z',
    insights: [
      'You send birthday emails to 92% of clients',
      'Average response time: within 24 hours of birthday',
      'High open rate (78%) for birthday emails',
    ],
    dataPoints: 23,
  },
  {
    id: 'adapt-002',
    type: 'sequence_adapted',
    title: 'Welcome Sequence Timing Adjusted',
    description: 'Adjusted welcome email timing based on observed client engagement patterns',
    timestamp: '2024-12-13T16:00:00Z',
    relatedAutomationId: 'auto-001',
    relatedAutomationName: 'New Client Welcome Sequence',
    insights: [
      'Morning sends (8-10 AM) have 35% higher open rates',
      'Tuesday-Thursday sends perform best',
    ],
    dataPoints: 34,
  },
  {
    id: 'adapt-003',
    type: 'preference_inferred',
    title: 'Communication Preference Learned',
    description: 'Learned that you prefer phone calls over emails for high-value clients',
    timestamp: '2024-12-12T14:30:00Z',
    insights: [
      'Phone calls used for 85% of clients with AUM > $500k',
      'Email used for routine updates regardless of client tier',
    ],
    dataPoints: 67,
  },
  {
    id: 'adapt-004',
    type: 'automation_learned',
    title: 'Meeting Prep Automation Created',
    description: 'System learned your meeting preparation workflow and created automation suggestion',
    timestamp: '2024-12-11T09:00:00Z',
    insights: [
      'You review client portfolios 1 day before meetings',
      'You prepare agenda notes 2 hours before meetings',
      'You check recent communications before each meeting',
    ],
    dataPoints: 45,
  },
  {
    id: 'adapt-005',
    type: 'pattern_detected',
    title: 'Follow-up Pattern Identified',
    description: 'Identified consistent 3-day follow-up pattern after sending important documents',
    timestamp: '2024-12-10T11:00:00Z',
    insights: [
      'Follow-ups sent 3 days after 87% of document sends',
      'Follow-up emails have 62% response rate',
    ],
    dataPoints: 18,
  },
];

// Automation activity log
export const mockAutomationActivity: AutomationActivityEntry[] = [
  {
    id: 'act-001',
    automationId: 'auto-002',
    automationName: 'Meeting Reminder Notifications',
    action: 'Sent meeting reminder',
    status: 'success',
    timestamp: '2024-12-15T08:00:00Z',
    affectedClientId: 'c-001',
    affectedClientName: 'Michael Johnson',
    details: 'Reminder for portfolio review meeting tomorrow at 2 PM',
    linkTo: { type: 'client', id: 'c-001' },
  },
  {
    id: 'act-002',
    automationId: 'auto-003',
    automationName: 'Document Expiry Alerts',
    action: 'Created expiry alert task',
    status: 'success',
    timestamp: '2024-12-15T06:00:00Z',
    affectedClientId: 'c-002',
    affectedClientName: 'Sarah Chen',
    details: 'Driver\'s license expiring in 28 days',
    linkTo: { type: 'task', id: 't-new-001' },
  },
  {
    id: 'act-003',
    automationId: 'auto-001',
    automationName: 'New Client Welcome Sequence',
    action: 'Sent welcome email',
    status: 'success',
    timestamp: '2024-12-14T15:30:00Z',
    affectedClientId: 'c-new-001',
    affectedClientName: 'Jennifer Martinez',
    details: 'Welcome email sent with getting started guide',
    linkTo: { type: 'client', id: 'c-new-001' },
  },
  {
    id: 'act-004',
    automationId: 'auto-001',
    automationName: 'New Client Welcome Sequence',
    action: 'Failed to send welcome email',
    status: 'failed',
    timestamp: '2024-12-14T15:35:00Z',
    affectedClientId: 'c-002',
    affectedClientName: 'Sarah Chen',
    details: 'Email bounced - invalid address',
  },
  {
    id: 'act-005',
    automationId: 'auto-005',
    automationName: 'Quarterly Review Scheduler',
    action: 'Scheduled quarterly review',
    status: 'success',
    timestamp: '2024-12-14T10:00:00Z',
    affectedClientId: 'c-003',
    affectedClientName: 'Robert Williams',
    details: 'Meeting scheduled for January 15, 2025 at 10 AM',
    linkTo: { type: 'client', id: 'c-003' },
  },
  {
    id: 'act-006',
    automationId: 'auto-002',
    automationName: 'Meeting Reminder Notifications',
    action: 'Sent meeting reminder',
    status: 'success',
    timestamp: '2024-12-14T08:00:00Z',
    affectedClientId: 'c-004',
    affectedClientName: 'Emily Davis',
    details: 'Reminder for financial planning session',
    linkTo: { type: 'client', id: 'c-004' },
  },
  {
    id: 'act-007',
    automationId: 'auto-003',
    automationName: 'Document Expiry Alerts',
    action: 'Created expiry alert task',
    status: 'success',
    timestamp: '2024-12-14T06:00:00Z',
    affectedClientId: 'c-001',
    affectedClientName: 'Michael Johnson',
    details: 'Insurance policy expiring in 25 days',
    linkTo: { type: 'task', id: 't-new-002' },
  },
  {
    id: 'act-008',
    automationId: 'auto-004',
    automationName: 'Post-Meeting Notes Reminder',
    action: 'Created notes reminder task',
    status: 'success',
    timestamp: '2024-12-10T17:00:00Z',
    affectedClientId: 'c-002',
    affectedClientName: 'Sarah Chen',
    details: 'Reminder to add notes for meeting that ended at 4 PM',
    linkTo: { type: 'task', id: 't-notes-001' },
  },
];
