import type { PrefilledMaterial } from '@/types/task';

export const MOCK_MATERIALS: PrefilledMaterial[] = [
  {
    id: 'mat-1',
    type: 'document',
    name: 'Q4 Portfolio Review - Johnson',
    description: 'Quarterly portfolio performance report with rebalancing recommendations',
    clientId: '1',
    clientName: 'Michael Johnson',
    relatedTaskId: '1',
    relatedWorkflowId: 'wf-1',
    status: 'ready',
    prefilledFields: 24,
    totalFields: 24,
    createdAt: '2025-12-04T08:30:00.000Z',
    updatedAt: '2025-12-04T08:30:00.000Z',
  },
  {
    id: 'mat-2',
    type: 'template',
    name: 'RRSP Contribution Reminder Email',
    description: 'Personalized email template for Sarah Chen with contribution room details',
    clientId: '2',
    clientName: 'Sarah Chen',
    relatedTaskId: '2',
    status: 'ready',
    prefilledFields: 8,
    totalFields: 8,
    createdAt: '2025-12-04T07:15:00.000Z',
    updatedAt: '2025-12-04T07:15:00.000Z',
  },
  {
    id: 'mat-3',
    type: 'checklist',
    name: 'Annual Review Meeting Checklist - Johnson',
    description: 'Pre-meeting preparation checklist for annual review',
    clientId: '1',
    clientName: 'Michael Johnson',
    relatedWorkflowId: 'wf-1',
    status: 'draft',
    prefilledFields: 12,
    totalFields: 15,
    createdAt: '2025-12-04T09:00:00.000Z',
    updatedAt: '2025-12-04T09:00:00.000Z',
    items: [
      { id: 'c1-1', text: 'Review portfolio performance report', completed: true, completedAt: '2025-12-04T09:30:00.000Z' },
      { id: 'c1-2', text: 'Prepare rebalancing recommendations', completed: true, completedAt: '2025-12-04T10:00:00.000Z' },
      { id: 'c1-3', text: 'Update client profile with recent changes', completed: false },
      { id: 'c1-4', text: 'Review tax implications of recommendations', completed: false },
      { id: 'c1-5', text: 'Prepare meeting agenda', completed: false },
      { id: 'c1-6', text: 'Book meeting room', completed: false },
      { id: 'c1-7', text: 'Send calendar invite', completed: false },
    ],
  },
  {
    id: 'mat-4',
    type: 'form',
    name: 'ESG Investment Selection Form - Rodriguez',
    description: 'Investment selection form for ESG portfolio allocation',
    clientId: '7',
    clientName: 'Lisa Rodriguez',
    relatedTaskId: '12',
    status: 'ready',
    prefilledFields: 15,
    totalFields: 18,
    createdAt: '2025-12-13T14:20:00.000Z',
    updatedAt: '2025-12-13T14:20:00.000Z',
  },
  {
    id: 'mat-5',
    type: 'report',
    name: 'RESP Annual Report - Zhang Family',
    description: 'Annual RESP performance summary for all three children',
    clientId: '10',
    clientName: 'Kevin and Jennifer Zhang',
    relatedTaskId: '15',
    status: 'ready',
    prefilledFields: 32,
    totalFields: 32,
    createdAt: '2025-12-13T16:45:00.000Z',
    updatedAt: '2025-12-13T16:45:00.000Z',
  },
  {
    id: 'mat-6',
    type: 'checklist',
    name: 'Estate Planning Review Checklist - O\'Connor',
    description: 'Comprehensive checklist for estate document review',
    clientId: '9',
    clientName: 'Margaret O\'Connor',
    relatedTaskId: '14',
    relatedWorkflowId: 'wf-3',
    status: 'draft',
    prefilledFields: 5,
    totalFields: 12,
    createdAt: '2025-12-09T11:00:00.000Z',
    updatedAt: '2025-12-09T11:00:00.000Z',
    items: [
      { id: 'c6-1', text: 'Review current will', completed: true, completedAt: '2025-12-09T11:30:00.000Z' },
      { id: 'c6-2', text: 'Check Power of Attorney documents', completed: true, completedAt: '2025-12-09T11:45:00.000Z' },
      { id: 'c6-3', text: 'Verify beneficiary designations on all accounts', completed: false },
      { id: 'c6-4', text: 'Review property ownership titles', completed: false },
      { id: 'c6-5', text: 'Check insurance policy beneficiaries', completed: false },
      { id: 'c6-6', text: 'Document any recent family changes', completed: false },
      { id: 'c6-7', text: 'Prepare summary of recommended updates', completed: false },
      { id: 'c6-8', text: 'Schedule meeting with estate attorney', completed: false },
    ],
  },
  {
    id: 'mat-7',
    type: 'document',
    name: 'TFSA vs Down Payment Analysis - Hassan',
    description: 'Financial analysis comparing TFSA maximization vs larger down payment',
    clientId: '8',
    clientName: 'Ahmed Hassan',
    relatedTaskId: '19',
    status: 'ready',
    prefilledFields: 20,
    totalFields: 20,
    createdAt: '2025-12-14T09:30:00.000Z',
    updatedAt: '2025-12-14T09:30:00.000Z',
  },
  {
    id: 'mat-8',
    type: 'template',
    name: 'Q4 Market Commentary Template',
    description: 'Quarterly market update template for all clients',
    relatedTaskId: '6',
    status: 'draft',
    prefilledFields: 10,
    totalFields: 15,
    createdAt: '2025-12-04T08:00:00.000Z',
    updatedAt: '2025-12-04T08:00:00.000Z',
  },
  {
    id: 'mat-9',
    type: 'checklist',
    name: 'Tax Loss Harvesting Checklist',
    description: 'Year-end tax loss harvesting review checklist',
    relatedTaskId: '9',
    relatedWorkflowId: 'wf-2',
    status: 'draft',
    prefilledFields: 6,
    totalFields: 10,
    createdAt: '2025-12-10T08:00:00.000Z',
    updatedAt: '2025-12-10T08:00:00.000Z',
    items: [
      { id: 'c9-1', text: 'Identify positions with unrealized losses', completed: true, completedAt: '2025-12-10T14:00:00.000Z' },
      { id: 'c9-2', text: 'Check for superficial loss rules', completed: true, completedAt: '2025-12-10T14:30:00.000Z' },
      { id: 'c9-3', text: 'Calculate potential tax savings', completed: true, completedAt: '2025-12-10T15:00:00.000Z' },
      { id: 'c9-4', text: 'Identify replacement securities', completed: false },
      { id: 'c9-5', text: 'Document trade rationale', completed: false },
      { id: 'c9-6', text: 'Execute approved trades', completed: false },
    ],
  },
];
