import type { Opportunity } from '@/types/opportunity';

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  // Contract-based opportunities
  {
    id: 'opp-1',
    clientId: '1',
    clientName: 'Michael Johnson',
    type: 'contract',
    title: 'RRSP Contribution Window Closing',
    description: 'Michael has $28,500 in unused RRSP contribution room. The deadline for 2025 tax year contributions is approaching (March 1, 2026).',
    whyNow: 'Only 10 weeks left to maximize 2025 tax benefits with $28,500 contribution room available.',
    whyNowDetails: 'Michael is in a high tax bracket and could save approximately $11,400 in taxes with a full contribution. His current cash position and income allow for this contribution without impacting liquidity needs.',
    impactScore: 88,
    impactLevel: 'high',
    estimatedValue: 11400,
    readiness: 'ready',
    readinessNotes: 'Client has liquid funds available. Previous discussions indicated interest in maximizing contributions.',
    sourceType: 'contribution_room',
    sourceDescription: 'Annual RRSP contribution room analysis',
    surfacedAt: '2025-12-10T08:00:00.000Z',
    expiresAt: '2026-03-01T23:59:59.000Z',
    status: 'new',
    suggestedWorkflow: 'tax_planning',
    suggestedWorkflowName: 'Tax Planning Review',
    tags: ['rrsp', 'tax-optimization', 'year-end'],
    priority: 95
  },
  {
    id: 'opp-2',
    clientId: '4',
    clientName: 'Robert Thompson',
    type: 'contract',
    title: 'GIC Maturity - Reinvestment Decision',
    description: 'Robert has a $150,000 GIC maturing on January 15, 2026. Current rates are favorable for renewal.',
    whyNow: 'GIC maturing in 4 weeks. Interest rates may decline - lock in current rates for better returns.',
    whyNowDetails: 'The maturing GIC was earning 3.8%. Current 5-year GIC rates are at 4.5%, offering an opportunity for improved income. Robert\'s conservative profile makes GICs ideal.',
    impactScore: 72,
    impactLevel: 'medium',
    estimatedValue: 6750,
    readiness: 'ready',
    prerequisites: ['Review current rate options', 'Confirm client liquidity needs'],
    sourceType: 'contract_expiry',
    sourceDescription: 'GIC maturity tracking',
    sourceId: 'gic-rt-001',
    surfacedAt: '2025-12-08T10:00:00.000Z',
    expiresAt: '2026-01-15T00:00:00.000Z',
    status: 'viewed',
    suggestedWorkflow: 'portfolio_rebalance',
    suggestedWorkflowName: 'Portfolio Rebalancing',
    tags: ['gic', 'fixed-income', 'reinvestment'],
    priority: 80
  },
  {
    id: 'opp-3',
    clientId: '9',
    clientName: "Margaret O'Connor",
    type: 'contract',
    title: 'Insurance Policy Annual Review Due',
    description: 'Life insurance policy is due for annual review. Coverage may need adjustment based on estate planning changes.',
    whyNow: 'Annual review window. Recent estate planning discussions suggest coverage review is timely.',
    whyNowDetails: 'Margaret\'s policy was last reviewed 14 months ago. Her estate plan has been updated to include grandchildren, which may affect beneficiary designations and coverage amounts.',
    impactScore: 65,
    impactLevel: 'medium',
    estimatedValue: 2400,
    readiness: 'needs_prep',
    readinessNotes: 'Need to obtain current policy documents from carrier',
    prerequisites: ['Request current policy statement', 'Review estate planning documents'],
    sourceType: 'policy_renewal',
    sourceDescription: 'Insurance policy review calendar',
    sourceId: 'ins-moc-001',
    surfacedAt: '2025-12-05T09:00:00.000Z',
    expiresAt: '2026-01-31T00:00:00.000Z',
    status: 'new',
    suggestedWorkflow: 'estate_planning',
    suggestedWorkflowName: 'Estate Planning Review',
    tags: ['insurance', 'estate-planning', 'annual-review'],
    priority: 70
  },
  {
    id: 'opp-4',
    clientId: '3',
    clientName: 'David and Emily Williams',
    type: 'contract',
    title: 'RRIF Minimum Withdrawal Planning',
    description: 'David turns 72 next year and must convert RRSP to RRIF. Planning for minimum withdrawals and tax implications.',
    whyNow: 'Mandatory RRIF conversion approaching. Early planning ensures optimal withdrawal strategy.',
    whyNowDetails: 'David\'s RRSP of $420,000 must be converted to a RRIF by December 31, 2026. Starting discussions now allows time to plan withdrawal strategy and coordinate with Emily\'s income for tax efficiency.',
    impactScore: 78,
    impactLevel: 'high',
    estimatedValue: 8500,
    readiness: 'needs_prep',
    readinessNotes: 'Need income projection for both David and Emily',
    prerequisites: ['Prepare retirement income projection', 'Review CPP/OAS claiming strategy'],
    sourceType: 'contract_expiry',
    sourceDescription: 'RRSP to RRIF conversion tracking',
    surfacedAt: '2025-12-01T08:00:00.000Z',
    expiresAt: '2026-12-31T00:00:00.000Z',
    status: 'new',
    suggestedWorkflow: 'annual_review',
    suggestedWorkflowName: 'Annual Review',
    tags: ['rrif', 'retirement-income', 'tax-planning'],
    priority: 85
  },

  // Milestone-based opportunities
  {
    id: 'opp-5',
    clientId: '2',
    clientName: 'Sarah Chen',
    type: 'milestone',
    title: 'Upcoming 40th Birthday - Financial Review',
    description: 'Sarah turns 40 in September 2025. A milestone birthday is a good time for comprehensive financial review.',
    whyNow: 'Milestone birthday approaching. Great opportunity for mid-career financial planning discussion.',
    whyNowDetails: 'At 40, Sarah is entering peak earning years. This is ideal timing to review long-term goals, insurance needs, and retirement trajectory. Her aggressive risk profile may need recalibration.',
    impactScore: 55,
    impactLevel: 'medium',
    estimatedValue: 3500,
    readiness: 'ready',
    sourceType: 'milestone_birthday',
    sourceDescription: 'Client birthday tracking - significant milestone',
    surfacedAt: '2025-12-12T07:00:00.000Z',
    expiresAt: '2025-09-30T00:00:00.000Z',
    status: 'new',
    suggestedWorkflow: 'annual_review',
    suggestedWorkflowName: 'Annual Review',
    tags: ['milestone', 'financial-review', 'life-stage'],
    priority: 60
  },
  {
    id: 'opp-6',
    clientId: '5',
    clientName: 'Priya Patel',
    type: 'milestone',
    title: 'Child Approaching High School - RESP Check',
    description: 'Priya\'s oldest child turns 14 next month. Time to review RESP investment strategy as post-secondary approaches.',
    whyNow: '4 years until potential RESP withdrawals. Shift to more conservative investments to protect gains.',
    whyNowDetails: 'The RESP for the oldest child has grown to $42,000. With 4 years until potential university enrollment, it\'s time to reduce equity exposure and protect accumulated gains.',
    impactScore: 68,
    impactLevel: 'medium',
    estimatedValue: 4200,
    readiness: 'ready',
    sourceType: 'milestone_birthday',
    sourceDescription: 'Dependent age milestone tracking',
    surfacedAt: '2025-12-09T08:00:00.000Z',
    expiresAt: '2026-06-30T00:00:00.000Z',
    status: 'viewed',
    suggestedWorkflow: 'portfolio_rebalance',
    suggestedWorkflowName: 'Portfolio Rebalancing',
    tags: ['resp', 'education-planning', 'risk-management'],
    priority: 72
  },
  {
    id: 'opp-7',
    clientId: '8',
    clientName: 'Ahmed Hassan',
    type: 'milestone',
    title: 'First Wedding Anniversary - Insurance Review',
    description: 'Ahmed got married last year. First anniversary is a good time to review insurance and beneficiary designations.',
    whyNow: 'Life change milestone. Insurance and estate documents may need updating for new marital status.',
    whyNowDetails: 'As a physician with high income, Ahmed should consider life and disability insurance updates now that he\'s married. Beneficiary designations on all accounts should reflect his spouse.',
    impactScore: 62,
    impactLevel: 'medium',
    estimatedValue: 5600,
    readiness: 'needs_prep',
    readinessNotes: 'Need to review current insurance coverage details',
    prerequisites: ['Obtain current insurance policy details', 'Review beneficiary designations'],
    sourceType: 'milestone_anniversary',
    sourceDescription: 'Marriage anniversary tracking',
    surfacedAt: '2025-12-11T09:00:00.000Z',
    expiresAt: '2026-03-15T00:00:00.000Z',
    status: 'new',
    suggestedWorkflow: 'insurance_renewal',
    suggestedWorkflowName: 'Insurance Review',
    tags: ['insurance', 'life-event', 'beneficiaries'],
    priority: 65
  },
  {
    id: 'opp-8',
    clientId: '7',
    clientName: 'Lisa Rodriguez',
    type: 'milestone',
    title: 'Inheritance Allocation Follow-up',
    description: 'Lisa received $200,000 inheritance 3 months ago. Follow up on investment allocation decisions.',
    whyNow: 'Inheritance funds have been in cash for 3 months. Time to finalize investment strategy.',
    whyNowDetails: 'The inheritance is currently earning minimal interest in a savings account. Lisa expressed interest in ESG investments during initial discussions. She\'s missed potential market gains during this period.',
    impactScore: 82,
    impactLevel: 'high',
    estimatedValue: 12000,
    readiness: 'ready',
    readinessNotes: 'ESG portfolio proposal already prepared',
    sourceType: 'life_event',
    sourceDescription: 'Inheritance tracking and follow-up',
    surfacedAt: '2025-12-07T10:00:00.000Z',
    expiresAt: '2026-01-31T00:00:00.000Z',
    status: 'new',
    suggestedWorkflow: 'client_onboarding',
    suggestedWorkflowName: 'New Asset Onboarding',
    tags: ['inheritance', 'esg', 'new-assets'],
    priority: 88
  },

  // Market-based opportunities
  {
    id: 'opp-9',
    clientId: '6',
    clientName: 'James Morrison',
    type: 'market',
    title: 'Private Equity Fund Opportunity',
    description: 'New private equity real estate fund opening to accredited investors. Matches James\'s interest in alternatives.',
    whyNow: 'Limited allocation available. Fund closes to new investors January 31, 2026.',
    whyNowDetails: 'The Maple Real Estate Partners Fund II is accepting new investors with a $100,000 minimum. Given James\'s real estate background and interest in alternatives, this aligns well with his portfolio objectives.',
    impactScore: 75,
    impactLevel: 'high',
    estimatedValue: 15000,
    readiness: 'needs_prep',
    readinessNotes: 'Need to verify accredited investor status and obtain subscription documents',
    prerequisites: ['Confirm accredited investor qualification', 'Review fund offering memorandum'],
    sourceType: 'product_launch',
    sourceDescription: 'Alternative investment product monitoring',
    surfacedAt: '2025-12-06T14:00:00.000Z',
    expiresAt: '2026-01-31T00:00:00.000Z',
    status: 'viewed',
    suggestedWorkflow: 'portfolio_rebalance',
    suggestedWorkflowName: 'Portfolio Rebalancing',
    tags: ['alternatives', 'private-equity', 'real-estate'],
    priority: 78
  },
  {
    id: 'opp-10',
    clientId: '10',
    clientName: 'Kevin and Jennifer Zhang',
    type: 'market',
    title: 'RESP Grant Top-up Opportunity',
    description: 'Government announced temporary RESP grant enhancement for 2026. Additional 10% on first $500 per child.',
    whyNow: 'Limited-time government incentive. Maximize contributions before enhancement period ends.',
    whyNowDetails: 'With three children, the Zhang family can receive an additional $150 in grants (3 x $50) by contributing $500 per child in January 2026. This is on top of regular CESG grants.',
    impactScore: 58,
    impactLevel: 'medium',
    estimatedValue: 1650,
    readiness: 'ready',
    sourceType: 'regulatory_change',
    sourceDescription: 'Government program updates monitoring',
    surfacedAt: '2025-12-13T11:00:00.000Z',
    expiresAt: '2026-02-28T00:00:00.000Z',
    status: 'new',
    suggestedWorkflow: 'tax_planning',
    suggestedWorkflowName: 'Tax Planning Review',
    tags: ['resp', 'government-grants', 'education'],
    priority: 62
  },
  {
    id: 'opp-11',
    clientId: '1',
    clientName: 'Michael Johnson',
    type: 'market',
    title: 'ESG Bond Fund Launch',
    description: 'New ESG-focused bond fund launching with attractive yield. Matches Michael\'s ESG interest and fixed income needs.',
    whyNow: 'Fund launch pricing available until January 15. Early investors get reduced MER.',
    whyNowDetails: 'The Sustainable Income Bond Fund offers a 4.2% yield with a 0.35% MER (reduced from 0.55% for launch subscribers). Michael has expressed interest in ESG investments and needs fixed income exposure.',
    impactScore: 52,
    impactLevel: 'medium',
    estimatedValue: 2800,
    readiness: 'ready',
    sourceType: 'product_launch',
    sourceDescription: 'New product monitoring - ESG fixed income',
    surfacedAt: '2025-12-12T08:00:00.000Z',
    expiresAt: '2026-01-15T00:00:00.000Z',
    status: 'new',
    suggestedWorkflow: 'portfolio_rebalance',
    suggestedWorkflowName: 'Portfolio Rebalancing',
    tags: ['esg', 'fixed-income', 'new-product'],
    priority: 55
  },
  {
    id: 'opp-12',
    clientId: '2',
    clientName: 'Sarah Chen',
    type: 'market',
    title: 'Tech Sector Pullback - Buying Opportunity',
    description: 'Recent tech sector correction creates buying opportunity for Sarah\'s growth-focused portfolio.',
    whyNow: 'Tech valuations at 6-month low. Sarah\'s high risk tolerance and US equity interest align with opportunity.',
    whyNowDetails: 'The tech-heavy NASDAQ has pulled back 12% from recent highs. Sarah\'s aggressive profile and interest in US equity exposure make this a potential buying opportunity to add positions at lower valuations.',
    impactScore: 70,
    impactLevel: 'high',
    estimatedValue: 8500,
    readiness: 'ready',
    sourceType: 'market_condition',
    sourceDescription: 'Market condition analysis and alerts',
    surfacedAt: '2025-12-14T07:00:00.000Z',
    expiresAt: '2026-01-31T00:00:00.000Z',
    status: 'new',
    suggestedWorkflow: 'portfolio_rebalance',
    suggestedWorkflowName: 'Portfolio Rebalancing',
    tags: ['tech', 'market-timing', 'growth'],
    priority: 75
  },

  // Additional opportunities for variety
  {
    id: 'opp-13',
    clientId: '3',
    clientName: 'David and Emily Williams',
    type: 'milestone',
    title: 'Adult Child Wedding - Estate Planning Update',
    description: 'Williams\' daughter is getting married next spring. Estate planning documents should be reviewed.',
    whyNow: 'Family structure changing. Estate documents should reflect new family dynamics.',
    whyNowDetails: 'When children marry, estate plans should be reviewed to consider in-law dynamics, potential grandchildren, and updated beneficiary designations. This is also a natural time to discuss wealth transfer strategies.',
    impactScore: 60,
    impactLevel: 'medium',
    estimatedValue: 4500,
    readiness: 'needs_prep',
    readinessNotes: 'Need to schedule family meeting to discuss goals',
    prerequisites: ['Review current will and POA documents', 'Discuss inter-generational wealth transfer'],
    sourceType: 'life_event',
    sourceDescription: 'Family milestone tracking',
    surfacedAt: '2025-12-08T09:00:00.000Z',
    expiresAt: '2026-05-01T00:00:00.000Z',
    status: 'snoozed',
    snoozedUntil: '2026-01-15T00:00:00.000Z',
    snoozeReason: 'Client requested follow-up after holidays',
    suggestedWorkflow: 'estate_planning',
    suggestedWorkflowName: 'Estate Planning Review',
    tags: ['estate-planning', 'family', 'wealth-transfer'],
    priority: 58
  },
  {
    id: 'opp-14',
    clientId: '6',
    clientName: 'James Morrison',
    type: 'contract',
    title: 'TFSA Contribution Room Reset',
    description: 'New year brings fresh TFSA contribution room. James has historically maxed contributions.',
    whyNow: 'January 1 brings new $7,000 contribution room. Early contribution maximizes tax-free growth.',
    whyNowDetails: 'James has maximized his TFSA every year. With $7,000 new room available January 1, 2026, and his high income, early contribution allows for maximum tax-free compounding throughout the year.',
    impactScore: 45,
    impactLevel: 'low',
    estimatedValue: 980,
    readiness: 'ready',
    sourceType: 'contribution_room',
    sourceDescription: 'Annual contribution room tracking',
    surfacedAt: '2025-12-14T08:00:00.000Z',
    expiresAt: '2026-12-31T00:00:00.000Z',
    status: 'new',
    suggestedWorkflow: 'tax_planning',
    suggestedWorkflowName: 'Tax Planning Review',
    tags: ['tfsa', 'annual-contribution', 'tax-optimization'],
    priority: 40
  },
  {
    id: 'opp-15',
    clientId: '5',
    clientName: 'Priya Patel',
    type: 'market',
    title: 'Small-Cap Canadian Equity Opportunity',
    description: 'Small-cap Canadian stocks showing value characteristics. Matches Priya\'s stated interest.',
    whyNow: 'Small-cap valuations at multi-year lows relative to large-caps. Potential for mean reversion.',
    whyNowDetails: 'Priya expressed interest in small-cap Canadian equities during her last review. The S&P/TSX Small Cap Index is trading at a 25% discount to historical P/E ratios, suggesting potential value.',
    impactScore: 48,
    impactLevel: 'low',
    estimatedValue: 2200,
    readiness: 'ready',
    sourceType: 'market_condition',
    sourceDescription: 'Client interest matching with market conditions',
    surfacedAt: '2025-12-11T14:00:00.000Z',
    status: 'dismissed',
    dismissReason: 'Client prefers to wait for more market stability',
    suggestedWorkflow: 'portfolio_rebalance',
    suggestedWorkflowName: 'Portfolio Rebalancing',
    tags: ['small-cap', 'canadian-equity', 'value'],
    priority: 45
  }
];
