import type { ProcessRecommendation } from '@/types/task';

export const MOCK_RECOMMENDATIONS: ProcessRecommendation[] = [
  {
    id: 'rec-1',
    type: 'automation',
    title: 'Automate RRSP Contribution Reminders',
    description: 'Set up automated email reminders for clients with RRSP contribution room 60 days before deadline.',
    expectedBenefit: 'Save 3-4 hours per month during RRSP season. Ensure no client misses the deadline.',
    impactLevel: 'high',
    effort: 'low',
    status: 'pending',
    suggestedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rec-2',
    type: 'efficiency',
    title: 'Batch Similar Client Reviews',
    description: 'Group annual reviews for clients with similar portfolios (same risk profile, similar holdings) on consecutive days.',
    expectedBenefit: 'Reduce preparation time by 30% due to shared research. Complete 5 reviews in time of 4.',
    impactLevel: 'medium',
    effort: 'low',
    status: 'applied',
    appliedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    outcome: {
      tracked: true,
      beforeMetrics: { avgPrepTimeMinutes: 45, reviewsPerWeek: 4 },
      afterMetrics: { avgPrepTimeMinutes: 32, reviewsPerWeek: 5 },
      notes: 'Successfully reduced prep time. Clients haven\'t noticed any difference in quality.',
    },
    suggestedAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rec-3',
    type: 'timing',
    title: 'Optimal Client Call Times',
    description: 'Based on response patterns, schedule calls with high-net-worth clients before 10 AM or after 3 PM.',
    expectedBenefit: 'Increase call connection rate from 62% to estimated 85%. Reduce phone tag cycles.',
    impactLevel: 'medium',
    effort: 'low',
    status: 'pending',
    suggestedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rec-4',
    type: 'priority',
    title: 'Prioritize High-AUM Clients for Tax Season',
    description: 'Focus tax planning efforts on top 20% of clients by AUM first, as they have the most optimization opportunities.',
    expectedBenefit: 'Capture 80% of tax savings value with 20% of effort. Ensure highest-value clients are served first.',
    impactLevel: 'high',
    effort: 'low',
    status: 'pending',
    suggestedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rec-5',
    type: 'automation',
    title: 'Auto-Generate Meeting Notes',
    description: 'Enable AI transcription and summary generation for all client meetings.',
    expectedBenefit: 'Save 15-20 minutes per meeting on note-taking. Capture more details accurately.',
    impactLevel: 'high',
    effort: 'medium',
    status: 'applied',
    appliedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    outcome: {
      tracked: true,
      beforeMetrics: { noteTimeMinutes: 18, detailScore: 72 },
      afterMetrics: { noteTimeMinutes: 3, detailScore: 94 },
      notes: 'Massive time savings. Notes are more comprehensive than manual ones.',
    },
    suggestedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rec-6',
    type: 'delegation',
    title: 'Delegate Administrative Tasks',
    description: 'Routine CRM updates and trade confirmation checks can be handled by automated systems.',
    expectedBenefit: 'Free up 2-3 hours per week for client-facing activities.',
    impactLevel: 'medium',
    effort: 'medium',
    status: 'dismissed',
    suggestedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rec-7',
    type: 'efficiency',
    title: 'Template Library for Common Emails',
    description: 'Create a library of email templates for common client communications (welcome, review reminders, market updates).',
    expectedBenefit: 'Reduce email drafting time by 60%. Ensure consistent, professional communication.',
    impactLevel: 'medium',
    effort: 'medium',
    status: 'pending',
    suggestedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
