import type { ReviewQueueItem } from '@/types/review-queue';

export const MOCK_REVIEW_QUEUE: ReviewQueueItem[] = [
  // High confidence items
  {
    id: 'rq-001',
    type: 'client_data',
    sourceType: 'email',
    sourceName: 'Email from Michael Johnson',
    sourceId: 'email-1234',
    extractedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
    extractedData: [
      { fieldName: 'phone', value: '(416) 555-1234', confidence: 95, source: 'Email signature' },
      { fieldName: 'newAddress', value: '456 Bay Street, Suite 800', confidence: 88, source: 'Email body' },
      { fieldName: 'city', value: 'Toronto', confidence: 92, source: 'Email body' },
    ],
    confidenceScore: 92,
    confidenceLevel: 'high',
    suggestedClientId: 'client-1',
    suggestedClientName: 'Michael Johnson',
    matchReason: 'Email sender matches client email address',
    status: 'pending',
  },
  {
    id: 'rq-002',
    type: 'document',
    sourceType: 'file',
    sourceName: 'T4_Statement_2024.pdf',
    sourceId: 'file-5678',
    extractedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(), // 4 hours ago
    extractedData: [
      { fieldName: 'employerName', value: 'Tech Corp Inc.', confidence: 98, source: 'Box 54' },
      { fieldName: 'totalIncome', value: 125000, confidence: 99, source: 'Box 14' },
      { fieldName: 'taxDeducted', value: 32500, confidence: 99, source: 'Box 22' },
      { fieldName: 'year', value: '2024', confidence: 100, source: 'Header' },
    ],
    confidenceScore: 99,
    confidenceLevel: 'high',
    suggestedClientId: 'client-2',
    suggestedClientName: 'Sarah Chen',
    matchReason: 'SIN matches client record',
    status: 'pending',
  },
  {
    id: 'rq-003',
    type: 'contact_info',
    sourceType: 'integration',
    sourceName: 'Google Contacts Sync',
    extractedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    extractedData: [
      { fieldName: 'workEmail', value: 'robert.w@lawfirm.ca', confidence: 100, source: 'Google Contacts' },
      { fieldName: 'workPhone', value: '(416) 555-9999', confidence: 100, source: 'Google Contacts' },
      { fieldName: 'jobTitle', value: 'Senior Partner', confidence: 95, source: 'Google Contacts' },
    ],
    confidenceScore: 98,
    confidenceLevel: 'high',
    suggestedClientId: 'client-3',
    suggestedClientName: 'Robert Williams',
    matchReason: 'Contact name exact match',
    status: 'pending',
  },

  // Medium confidence items
  {
    id: 'rq-004',
    type: 'transaction',
    sourceType: 'file',
    sourceName: 'Investment_Statement_Q4.pdf',
    sourceId: 'file-9012',
    extractedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
    extractedData: [
      { fieldName: 'accountNumber', value: 'INV-88742', confidence: 95, source: 'Page 1 header' },
      { fieldName: 'totalValue', value: 487500, confidence: 92, source: 'Summary section' },
      { fieldName: 'quarterlyGain', value: 12500, confidence: 88, source: 'Performance section' },
      { fieldName: 'dividendsReceived', value: 3200, confidence: 85, source: 'Income section' },
    ],
    confidenceScore: 78,
    confidenceLevel: 'medium',
    suggestedClientId: 'client-4',
    suggestedClientName: 'Emily Thompson',
    matchReason: 'Account number partial match',
    alternativeMatches: [
      { clientId: 'client-5', clientName: 'David Lee', matchScore: 65, matchReason: 'Similar account prefix' },
    ],
    status: 'pending',
  },
  {
    id: 'rq-005',
    type: 'client_data',
    sourceType: 'email',
    sourceName: 'Re: Portfolio Update Request',
    sourceId: 'email-3456',
    extractedAt: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
    extractedData: [
      { fieldName: 'riskToleranceChange', value: 'moderate', confidence: 75, source: 'Email body' },
      { fieldName: 'investmentGoal', value: 'retirement in 10 years', confidence: 70, source: 'Email body' },
      { fieldName: 'additionalContribution', value: 50000, confidence: 82, source: 'Email body' },
    ],
    confidenceScore: 76,
    confidenceLevel: 'medium',
    suggestedClientId: 'client-1',
    suggestedClientName: 'Michael Johnson',
    matchReason: 'Email thread history',
    status: 'pending',
  },
  {
    id: 'rq-006',
    type: 'relationship',
    sourceType: 'file',
    sourceName: 'Marriage_Certificate.pdf',
    sourceId: 'file-1111',
    extractedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    extractedData: [
      { fieldName: 'spouseName', value: 'Jennifer Williams', confidence: 95, source: 'Certificate' },
      { fieldName: 'marriageDate', value: '2023-06-15', confidence: 98, source: 'Certificate' },
      { fieldName: 'relationshipType', value: 'spouse', confidence: 100, source: 'Document type' },
    ],
    confidenceScore: 72,
    confidenceLevel: 'medium',
    suggestedClientId: 'client-3',
    suggestedClientName: 'Robert Williams',
    matchReason: 'Name match on certificate',
    alternativeMatches: [
      { clientId: 'client-6', clientName: 'James Williams', matchScore: 55, matchReason: 'Same last name' },
    ],
    status: 'pending',
  },

  // Low confidence items
  {
    id: 'rq-007',
    type: 'client_data',
    sourceType: 'manual',
    sourceName: 'Voice Note Transcription',
    extractedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    extractedData: [
      { fieldName: 'meetingNotes', value: 'Client mentioned considering early retirement', confidence: 60, source: 'Transcription' },
      { fieldName: 'followUpDate', value: 'next month', confidence: 45, source: 'Transcription' },
      { fieldName: 'interestArea', value: 'pension options', confidence: 55, source: 'Transcription' },
    ],
    confidenceScore: 53,
    confidenceLevel: 'low',
    suggestedClientId: 'client-5',
    suggestedClientName: 'David Lee',
    matchReason: 'Mentioned name "David" in recording',
    alternativeMatches: [
      { clientId: 'client-7', clientName: 'David Park', matchScore: 45, matchReason: 'Also named David' },
    ],
    status: 'pending',
  },
  {
    id: 'rq-008',
    type: 'document',
    sourceType: 'file',
    sourceName: 'Scanned_Document_001.jpg',
    sourceId: 'file-2222',
    extractedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    extractedData: [
      { fieldName: 'documentType', value: 'Insurance Policy', confidence: 70, source: 'OCR Header' },
      { fieldName: 'policyNumber', value: 'POL-????-8821', confidence: 40, source: 'OCR - partial' },
      { fieldName: 'coverageAmount', value: 500000, confidence: 55, source: 'OCR Body' },
    ],
    confidenceScore: 48,
    confidenceLevel: 'low',
    matchReason: 'Unable to identify client - poor scan quality',
    status: 'pending',
  },
  {
    id: 'rq-009',
    type: 'contact_info',
    sourceType: 'calendar',
    sourceName: 'Meeting: Annual Review',
    sourceId: 'cal-7890',
    extractedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    extractedData: [
      { fieldName: 'preferredMeetingTime', value: 'Tuesdays 2pm', confidence: 85, source: 'Calendar event pattern' },
      { fieldName: 'meetingLocation', value: 'Video call', confidence: 90, source: 'Event location' },
    ],
    confidenceScore: 58,
    confidenceLevel: 'low',
    suggestedClientId: 'client-2',
    suggestedClientName: 'Sarah Chen',
    matchReason: 'Calendar event attendee email',
    alternativeMatches: [
      { clientId: 'client-8', clientName: 'Sarah Miller', matchScore: 40, matchReason: 'Similar first name' },
    ],
    status: 'pending',
  },

  // Already processed items
  {
    id: 'rq-010',
    type: 'client_data',
    sourceType: 'email',
    sourceName: 'Updated Contact Details',
    extractedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    extractedData: [
      { fieldName: 'newPhone', value: '(647) 555-4321', confidence: 95, source: 'Email body' },
    ],
    confidenceScore: 95,
    confidenceLevel: 'high',
    suggestedClientId: 'client-4',
    suggestedClientName: 'Emily Thompson',
    matchReason: 'Email exact match',
    status: 'approved',
    reviewedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rq-011',
    type: 'transaction',
    sourceType: 'integration',
    sourceName: 'Bank Feed - TD Account',
    extractedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    extractedData: [
      { fieldName: 'deposit', value: 25000, confidence: 100, source: 'Bank API' },
      { fieldName: 'accountBalance', value: 142350, confidence: 100, source: 'Bank API' },
    ],
    confidenceScore: 100,
    confidenceLevel: 'high',
    suggestedClientId: 'client-1',
    suggestedClientName: 'Michael Johnson',
    matchReason: 'Linked bank account',
    status: 'approved',
    reviewedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rq-012',
    type: 'document',
    sourceType: 'file',
    sourceName: 'Unknown_Receipt.pdf',
    extractedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    extractedData: [
      { fieldName: 'amount', value: 150, confidence: 80, source: 'OCR' },
    ],
    confidenceScore: 35,
    confidenceLevel: 'low',
    matchReason: 'No client match found',
    status: 'rejected',
    reviewedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    reviewNotes: 'Personal expense, not client-related',
  },
  {
    id: 'rq-013',
    type: 'contact_info',
    sourceType: 'email',
    sourceName: 'FW: New Address',
    extractedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    extractedData: [
      { fieldName: 'address', value: '789 King St W, Unit 1201', confidence: 90, source: 'Email body' },
      { fieldName: 'city', value: 'Toronto', confidence: 95, source: 'Email body' },
      { fieldName: 'postalCode', value: 'M5V 1N2', confidence: 92, source: 'Email body' },
    ],
    confidenceScore: 88,
    confidenceLevel: 'high',
    suggestedClientId: 'client-5',
    suggestedClientName: 'David Lee',
    matchReason: 'Email sender match',
    status: 'edited',
    reviewedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    reviewNotes: 'Corrected postal code to M5V 1N3',
  },
  {
    id: 'rq-014',
    type: 'relationship',
    sourceType: 'file',
    sourceName: 'Family_Trust_Document.pdf',
    extractedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    extractedData: [
      { fieldName: 'beneficiary1', value: 'Alex Thompson', confidence: 95, source: 'Trust document' },
      { fieldName: 'beneficiary2', value: 'Emma Thompson', confidence: 95, source: 'Trust document' },
      { fieldName: 'relationshipType', value: 'children', confidence: 98, source: 'Document context' },
    ],
    confidenceScore: 96,
    confidenceLevel: 'high',
    suggestedClientId: 'client-4',
    suggestedClientName: 'Emily Thompson',
    matchReason: 'Trustee name match',
    status: 'merged',
    reviewedAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
    reviewNotes: 'Merged with existing family relationship records',
  },
];
