import type { SuggestedAction } from '@/types/task';

export const MOCK_SUGGESTED_ACTIONS: SuggestedAction[] = [
  {
    id: 'sa-1',
    type: 'review_required',
    title: 'Review Johnson Portfolio Analysis',
    description: 'Ciri has completed the Q4 portfolio analysis. Review the recommendations before sharing with the client.',
    reason: 'The portfolio review task was auto-completed by Ciri with 92% confidence. As this involves investment recommendations, your review ensures accuracy and adds the personal touch clients expect.',
    clientId: '1',
    clientName: 'Michael Johnson',
    relatedTaskId: '1',
    priority: 'high',
    confidence: 95,
    suggestedAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    status: 'pending',
  },
  {
    id: 'sa-2',
    type: 'follow_up',
    title: 'Follow up with Sarah Chen on RRSP',
    description: 'Sarah viewed the RRSP reminder email 3 times but hasn\'t responded. A personal call may help.',
    reason: 'Email engagement analytics show high interest (3 opens, 2 link clicks) without action. Historical data suggests a follow-up call converts 78% of similar situations. RRSP deadline is approaching in March.',
    clientId: '2',
    clientName: 'Sarah Chen',
    relatedTaskId: '2',
    priority: 'medium',
    confidence: 78,
    suggestedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    status: 'pending',
  },
  {
    id: 'sa-3',
    type: 'schedule_meeting',
    title: 'Schedule Q1 Review with Williams',
    description: 'The Williams family retirement planning follow-up is due in January. Book the meeting now to secure a good time slot.',
    reason: 'Your action item from the December 3rd meeting specified a January follow-up. Your calendar shows limited availability in early January. Booking now ensures continuity.',
    clientId: '3',
    clientName: 'David and Emily Williams',
    priority: 'medium',
    confidence: 88,
    suggestedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    status: 'pending',
  },
  {
    id: 'sa-4',
    type: 'complete_task',
    title: 'Mark Thompson Call as Complete',
    description: 'Based on your calendar, the Thompson TFSA call occurred at 11 AM. Would you like to mark this task complete?',
    reason: 'Your calendar shows a completed call with Robert Thompson at 11:00 AM today. The associated task is still marked as pending.',
    clientId: '4',
    clientName: 'Robert Thompson',
    relatedTaskId: '4',
    priority: 'low',
    confidence: 92,
    suggestedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    status: 'pending',
  },
  {
    id: 'sa-5',
    type: 'send_document',
    title: 'Send ESG Portfolio Proposal to Rodriguez',
    description: 'The Ciri-drafted ESG investment proposal is ready. Send it to Lisa before your scheduled meeting.',
    reason: 'The email draft has been waiting for review for 24 hours. Your meeting with Lisa is in 2 days. Sending now gives her time to review before the discussion.',
    clientId: '7',
    clientName: 'Lisa Rodriguez',
    relatedTaskId: '12',
    priority: 'high',
    confidence: 85,
    suggestedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    status: 'pending',
  },
  {
    id: 'sa-6',
    type: 'escalate',
    title: 'Priority: O\'Connor Estate Documents Overdue',
    description: 'The estate planning document review for Margaret O\'Connor is approaching deadline with no progress.',
    reason: 'Task due date is December 22nd with no updates since creation on December 8th. Estate documents require legal review time. Recommend prioritizing this week.',
    clientId: '9',
    clientName: 'Margaret O\'Connor',
    relatedTaskId: '14',
    priority: 'high',
    confidence: 90,
    suggestedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    status: 'pending',
  },
  {
    id: 'sa-7',
    type: 'update_record',
    title: 'Update Hassan Home Purchase Timeline',
    description: 'Ahmed mentioned on your last call he\'s targeting a March purchase. Update the planning session to reflect new timeline.',
    reason: 'Call notes from December 10th indicate Ahmed is moving faster than expected. The current task is scheduled for January but may need to be expedited.',
    clientId: '8',
    clientName: 'Ahmed Hassan',
    relatedTaskId: '13',
    priority: 'medium',
    confidence: 72,
    suggestedAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    status: 'pending',
  },
];
