import type { Workflow } from '@/types/task';

export const MOCK_WORKFLOWS: Workflow[] = [
  {
    id: 'wf-1',
    type: 'annual_review',
    name: 'Annual Review - Michael Johnson',
    description: 'Complete annual portfolio review and planning session with Michael Johnson',
    clientId: '1',
    clientName: 'Michael Johnson',
    status: 'active',
    steps: [
      {
        id: 'wf-1-s1',
        name: 'Portfolio Performance Analysis',
        description: 'Analyze YTD performance and compare to benchmarks',
        status: 'completed',
        order: 1,
        estimatedMinutes: 30,
        actualMinutes: 25,
        completedAt: '2025-12-04T08:30:00.000Z',
        isAutomated: true,
      },
      {
        id: 'wf-1-s2',
        name: 'Review AI Recommendations',
        description: 'Review and approve AI-generated portfolio recommendations',
        status: 'in_progress',
        order: 2,
        estimatedMinutes: 15,
      },
      {
        id: 'wf-1-s3',
        name: 'Prepare Meeting Materials',
        description: 'Compile presentation deck and supporting documents',
        status: 'pending',
        order: 3,
        estimatedMinutes: 20,
        isAutomated: true,
      },
      {
        id: 'wf-1-s4',
        name: 'Schedule Annual Review Meeting',
        description: 'Book meeting room and send calendar invite',
        status: 'pending',
        order: 4,
        estimatedMinutes: 10,
      },
      {
        id: 'wf-1-s5',
        name: 'Conduct Meeting',
        description: 'Present findings and discuss next year\'s strategy',
        status: 'pending',
        order: 5,
        estimatedMinutes: 60,
      },
      {
        id: 'wf-1-s6',
        name: 'Document Action Items',
        description: 'Record meeting notes and create follow-up tasks',
        status: 'pending',
        order: 6,
        estimatedMinutes: 15,
        isAutomated: true,
      },
    ],
    createdAt: '2025-12-01T09:00:00.000Z',
    updatedAt: '2025-12-04T08:30:00.000Z',
    estimatedCompletionDate: '2025-12-18T17:00:00.000Z',
    relatedTaskIds: ['1', '7'],
  },
  {
    id: 'wf-2',
    type: 'tax_planning',
    name: 'Year-End Tax Planning - All Clients',
    description: 'Complete year-end tax optimization for high-income clients',
    status: 'active',
    steps: [
      {
        id: 'wf-2-s1',
        name: 'Identify Tax Loss Harvesting Opportunities',
        description: 'Review all portfolios for positions with unrealized losses',
        status: 'completed',
        order: 1,
        estimatedMinutes: 60,
        actualMinutes: 55,
        completedAt: '2025-12-10T14:00:00.000Z',
        isAutomated: true,
      },
      {
        id: 'wf-2-s2',
        name: 'Calculate RRSP Contribution Room',
        description: 'Verify contribution room for each client',
        status: 'completed',
        order: 2,
        estimatedMinutes: 45,
        actualMinutes: 40,
        completedAt: '2025-12-11T10:00:00.000Z',
        isAutomated: true,
      },
      {
        id: 'wf-2-s3',
        name: 'Prepare Individual Tax Strategies',
        description: 'Create personalized tax optimization recommendations',
        status: 'in_progress',
        order: 3,
        estimatedMinutes: 120,
      },
      {
        id: 'wf-2-s4',
        name: 'Client Communications',
        description: 'Send tax planning recommendations to each client',
        status: 'pending',
        order: 4,
        estimatedMinutes: 90,
      },
      {
        id: 'wf-2-s5',
        name: 'Execute Approved Trades',
        description: 'Implement approved tax loss harvesting trades',
        status: 'pending',
        order: 5,
        estimatedMinutes: 60,
      },
      {
        id: 'wf-2-s6',
        name: 'Document and Archive',
        description: 'Record all actions for tax documentation',
        status: 'pending',
        order: 6,
        estimatedMinutes: 30,
        isAutomated: true,
      },
    ],
    createdAt: '2025-12-10T08:00:00.000Z',
    updatedAt: '2025-12-13T11:15:00.000Z',
    estimatedCompletionDate: '2025-12-20T17:00:00.000Z',
    relatedTaskIds: ['9', '16'],
  },
  {
    id: 'wf-3',
    type: 'estate_planning',
    name: 'Estate Planning Review - Margaret O\'Connor',
    description: 'Comprehensive estate planning document review and update',
    clientId: '9',
    clientName: 'Margaret O\'Connor',
    status: 'active',
    steps: [
      {
        id: 'wf-3-s1',
        name: 'Gather Current Documents',
        description: 'Collect will, POA, and beneficiary designations',
        status: 'completed',
        order: 1,
        estimatedMinutes: 30,
        actualMinutes: 35,
        completedAt: '2025-12-09T11:00:00.000Z',
      },
      {
        id: 'wf-3-s2',
        name: 'Review Asset Ownership',
        description: 'Verify titling of all accounts and properties',
        status: 'pending',
        order: 2,
        estimatedMinutes: 45,
      },
      {
        id: 'wf-3-s3',
        name: 'Beneficiary Audit',
        description: 'Compare designated beneficiaries with estate wishes',
        status: 'pending',
        order: 3,
        estimatedMinutes: 30,
      },
      {
        id: 'wf-3-s4',
        name: 'Draft Recommendations',
        description: 'Prepare list of suggested updates',
        status: 'pending',
        order: 4,
        estimatedMinutes: 60,
      },
      {
        id: 'wf-3-s5',
        name: 'Client Review Meeting',
        description: 'Present findings and discuss changes',
        status: 'pending',
        order: 5,
        estimatedMinutes: 60,
      },
      {
        id: 'wf-3-s6',
        name: 'Coordinate with Legal',
        description: 'Work with estate attorney on document updates',
        status: 'pending',
        order: 6,
        estimatedMinutes: 45,
      },
    ],
    createdAt: '2025-12-08T14:00:00.000Z',
    updatedAt: '2025-12-09T11:00:00.000Z',
    estimatedCompletionDate: '2025-12-22T11:00:00.000Z',
    relatedTaskIds: ['14'],
  },
  {
    id: 'wf-4',
    type: 'client_onboarding',
    name: 'New Client Onboarding - James Morrison',
    description: 'Complete onboarding process for new high-net-worth client',
    clientId: '6',
    clientName: 'James Morrison',
    status: 'active',
    steps: [
      {
        id: 'wf-4-s1',
        name: 'KYC Documentation',
        description: 'Complete Know Your Client forms and verification',
        status: 'completed',
        order: 1,
        estimatedMinutes: 45,
        actualMinutes: 50,
        completedAt: '2025-12-05T10:00:00.000Z',
      },
      {
        id: 'wf-4-s2',
        name: 'Risk Assessment',
        description: 'Complete risk tolerance questionnaire and analysis',
        status: 'completed',
        order: 2,
        estimatedMinutes: 30,
        actualMinutes: 25,
        completedAt: '2025-12-06T14:00:00.000Z',
      },
      {
        id: 'wf-4-s3',
        name: 'Investment Policy Statement',
        description: 'Draft and approve IPS document',
        status: 'completed',
        order: 3,
        estimatedMinutes: 60,
        actualMinutes: 55,
        completedAt: '2025-12-08T16:00:00.000Z',
      },
      {
        id: 'wf-4-s4',
        name: 'Portfolio Construction',
        description: 'Design initial portfolio allocation',
        status: 'in_progress',
        order: 4,
        estimatedMinutes: 90,
      },
      {
        id: 'wf-4-s5',
        name: 'Account Funding',
        description: 'Coordinate asset transfers and funding',
        status: 'pending',
        order: 5,
        estimatedMinutes: 30,
      },
      {
        id: 'wf-4-s6',
        name: 'Implementation',
        description: 'Execute initial trades and set up monitoring',
        status: 'pending',
        order: 6,
        estimatedMinutes: 60,
      },
    ],
    createdAt: '2025-12-03T09:00:00.000Z',
    updatedAt: '2025-12-12T15:30:00.000Z',
    estimatedCompletionDate: '2025-12-20T17:00:00.000Z',
    relatedTaskIds: ['11', '17'],
  },
];
